# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Australia Configuration"
  lane :configure_for_australia do
    update_info_plist(
      plist_path: "GTWeather/Info.plist",
      display_name: "My Aussie Weather"
    )
  end

  desc "Canada Configuration"
  lane :configure_for_canada do
    update_info_plist(
      plist_path: "GTWeather/Info.plist",
      display_name: "My Eh Weather"
    )
  end
end
